name: "Nanoleaf2MQTT"
description: "A bridge between Nanoleaf devices and MQTT."
version: "0.1.1"
slug: "nanoleaf2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
host_network: true
hassio_api: true
