name: "Nanoleaf2MQTT"
description: "A bridge between Nanoleaf devices and MQTT."
version: "0.1.5"
slug: "nanoleaf2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
host_network: false
hassio_api: true
homeassistant_api: true
services:
  - mqtt:need
